server:
  port: 8084

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Add mail configuration for default profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedrofr1313@gmail.com
    password: bhyk eosi kjtc ukjq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      osrmRoute:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      osrmRoute:
        maxAttempts: 3
        waitDuration: 2s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/logistics_db
  rabbitmq:
    host: rabbitmq
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedrofr1313@gmail.com
    password: bhyk eosi kjtc ukjq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:

      default-zone: http://eureka-server:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

azure:
  function:
    email:
      url: https://functions-1750970564996.azurewebsites.net/api/SendEmail
      key: ${AZURE_FUNCTION_KEY:your-default-key}
