server:
  port: 0
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: mySecretKey1234567890123456789012345678901234567890
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/logistics_db

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka