server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
    
      routes:
       
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway
        url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka

# Configuração específica para Docker
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Gateway
        url: /v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs